class NewUsers < ActiveRecord::Migration
  def up
  	User.delete_all

  	default_image = Photo.find_by_name("profile-default").id.to_s

  	adam = User.new(:username => "adam", :image => default_image, :password =>  "adam",  :first_name => "Adam", :last_name => "Detzner", :description => "adetzner@stanford.edu")
	adam.save(:validate => false)
	alex = User.new(:username => "alex", :image => default_image, :password => "alex", :first_name => "Alex", :last_name => "Zannos", :description => "azannos@stanford.edu")
	alex.save(:validate => false)
	allison = User.new(:username => "allison", :image => default_image, :password => "allison", :first_name => "Allison", :last_name => "Semrad", :description => "asemrad@stanford.edu")
	allison.save(:validate => false)
	blanca = User.new(:username => "blanca", :image => default_image, :password => "blanca", :first_name => "Blanca", :last_name => "Villanueva", :description => "villanue@stanford.edu")
	blanca.save(:validate => false)
	bora = User.new(:username => "bora", :image => default_image, :password => "bora", :first_name => "Bora", :last_name => "Baydere", :description => "bbaydere@stanford.edu")
	bora.save(:validate => false)
	christian = User.new(:username => "christian", :image => default_image, :password => "christian", :first_name => "Christian", :last_name => "Leal", :description => "cleal93@stanford.edu")
	christian.save(:validate => false)
	claire = User.new(:username => "claire", :image => default_image, :password => "claire", :first_name => "Claire", :last_name => "Lynch", :description => "bear18@stanford.edu")
	claire.save(:validate => false)
	david = User.new(:username => "david", :image => default_image, :password => "david", :first_name => "David", :last_name => "Katosh", :description => "dkatosh@stanford.edu")
	david.save(:validate => false)
	edith = User.new(:username => "edith", :image => default_image, :password => "edith", :first_name => "Edith", :last_name => "Preciado", :description => "epreciad@stanford.edu")
	edith.save(:validate => false)
	james = User.new(:username => "james", :image => default_image, :password => "james", :first_name => "James", :last_name => "Cranston", :description => "jamesc4@stanford.edu")
	james.save(:validate => false)
	jon = User.new(:username => "jon", :image => default_image, :password => "jon", :first_name => "Jon", :last_name => "Renslo", :description => "jrenslo@stanford.edu")
	jon.save(:validate => false)
	cyjlo = User.new(:username => "cyjlo", :image => default_image, :password => "cyjlo", :first_name => "Jonathan", :last_name => "Lo", :description => "cyjlo@stanford.edu")
	cyjlo.save(:validate => false)
	jfullman = User.new(:username => "jfullman", :image => default_image, :password => "jfullman", :first_name => "Jonathan", :last_name => "Fullman", :description => "jfullman@stanford.edu")
	jfullman.save(:validate => false)
	joseph = User.new(:username => "joseph", :image => default_image, :password => "joseph", :first_name => "Joseph", :last_name => "Topasna", :description => "jtopasna@stanford.edu")
	joseph.save(:validate => false)
	jovel = User.new(:username => "jovel", :image => default_image, :password => "jovel", :first_name => "Jovel", :last_name => "Queirolo", :description => "jovelq@stanford.edu")
	jovel.save(:validate => false)
	lananh = User.new(:username => "lananh", :image => default_image, :password => "lananh", :first_name => "Lan Anh", :last_name => "Le", :description => "lananhle@stanford.edu")
	lananh.save(:validate => false)
	laurel = User.new(:username => "laurel", :image => default_image, :password => "laurel", :first_name => "Laurel", :last_name => "Fish", :description => "lfish@stanford.edu")
	laurel.save(:validate => false)
	leopold = User.new(:username => "leopold", :image => default_image, :password => "leopold", :first_name => "Leopold", :last_name => "Wambersie de Brouwer", :description => "leopoldw@stanford.edu")
	leopold.save(:validate => false)
	luis = User.new(:username => "luis", :image => default_image, :password => "luis", :first_name => "Luis", :last_name => "Aguilar", :description => "luis9151@stanford.edu")
	luis.save(:validate => false)
	matthew = User.new(:username => "matthew", :image => default_image, :password => "matthew", :first_name => "Matthew", :last_name => "Sach", :description => "mdsach@stanford.edu")
	matthew.save(:validate => false)
	mishlee = User.new(:username => "mishlee", :image => default_image, :password => "mishlee", :first_name => "Michelle", :last_name => "Lee", :description => "mishlee@stanford.edu")
	mishlee.save(:validate => false)
	mixue = User.new(:username => "mixue", :image => default_image, :password => "mixue", :first_name => "Michelle", :last_name => "Jia", :description => "mixue@stanford.edu")
	mixue.save(:validate => false)
	nathan = User.new(:username => "nathan", :image => default_image, :password => "nathan", :first_name => "Nathan", :last_name => "Boyne", :description => "njboyne@stanford.edu")
	nathan.save(:validate => false)
	pearle = User.new(:username => "pearle", :image => default_image, :password => "pearle", :first_name => "Pearle", :last_name => "Lun", :description => "plun@stanford.edu")
	pearle.save(:validate => false)
	quyen = User.new(:username => "quyen", :image => default_image, :password => "quyen", :first_name => "Quyen", :last_name => "Nguyen", :description => "quyenn14@stanford.edu")
	quyen.save(:validate => false)
	rachel = User.new(:username => "rachel", :image => default_image, :password => "rachel", :first_name => "Rachel", :last_name => "Hovde", :description => "rhovde@stanford.edu")
	rachel.save(:validate => false)
	rasmus = User.new(:username => "rasmus", :image => default_image, :password => "rasmus", :first_name => "Rasmus", :last_name => "Rygaard", :description => "rygaard@stanford.edu")
	rasmus.save(:validate => false)
	reno = User.new(:username => "reno", :image => default_image, :password => "reno", :first_name => "Reno", :last_name => "Tsosie", :description => "rtsosie@stanford.edu")
	reno.save(:validate => false)
	robert = User.new(:username => "robert", :image => default_image, :password => "robert", :first_name => "Robert", :last_name => "Carrera", :description => "rcarrera@stanford.edu")
	robert.save(:validate => false)
	sara = User.new(:username => "sara", :image => default_image, :password => "sara", :first_name => "Sara", :last_name => "Maurer", :description => "smaurer@stanford.edu")
	sara.save(:validate => false)
	sarah = User.new(:username => "sarah", :image => default_image, :password => "sarah", :first_name => "Sarah", :last_name => "Nader", :description => "snader2@stanford.edu")
	sarah.save(:validate => false)
	shannon = User.new(:username => "shannon", :image => default_image, :password => "shannon", :first_name => "Shannon", :last_name => "Schweitzer", :description => "sschweit@stanford.edu")
	shannon.save(:validate => false)
	shayda = User.new(:username => "shayda", :image => default_image, :password => "shayda", :first_name => "Shayda", :last_name => "Zarafshar", :description => "shaydaz@stanford.edu")
	shayda.save(:validate => false)
	sibel = User.new(:username => "sibel", :image => default_image, :password => "sibel", :first_name => "Sibel", :last_name => "Sayiner", :description => "ssayiner@stanford.edu")
	sibel.save(:validate => false)
	silviana = User.new(:username => "silviana", :image => default_image, :password => "silviana", :first_name => "Silviana", :last_name => "Ilcus", :description => "smci@stanford.edu")
	silviana.save(:validate => false)
	victor = User.new(:username => "victor", :image => default_image, :password => "victor", :first_name => "Victor", :last_name => "Verdejo", :description => "victor15@stanford.edu")
	victor.save(:validate => false)
	vilde = User.new(:username => "vilde", :image => default_image, :password => "vilde", :first_name => "Vilde", :last_name => "Opsal", :description => "vjopsal@stanford.edu")
vilde.save(:validate => false)
  end

  def down
  	User.delete_all
  end
end
